### ISSUE TITLE
Wrong linking: List in-progress conferences on or after a given date

### ISSUE THREAD

**Issue by nxz91** [twilio/sample-code#31]
The linked code here is supposed to show how to read the list of conferences that started on or after a given date: https://www.twilio.com/docs/voice/api/conference#read-list-in-progress-conferences-on-or-after-a-given-date

More like this file in C#: https://github.com/twilio/sample-code/blob/master/api/v2010/conference/read-example-4/read-example-4.4.x.cs

The 4.4.x code example for NodeJS seems to be missing entirely.

**Comment by coderkat** [comment]
Thanks so much for flagging this @nxz91 – I'm working on a fix right now to make sure we get the date filtering in these samples, will hopefully be able to merge it today.

[This node.js code]( https://github.com/TwilioDevEd/api-snippets/blob/master/rest/conference/list-get-example-4/list-get-example-4.3.x.js) should work with the latest Node helper library (but you'll probably want to do `console.log(conference.sid));` instead of logging the status).

As far as the Node samples go, the latest Twilio Node.js library is on version 3.x, which is why you're not seeing a 4.x in the list of options.

**Comment by coderkat** [comment]
All code samples in https://github.com/twilio/sample-code/tree/master/api/v2010/conference/read-example-4 now updated to show `on or after` filtering
